### ISSUE TITLE
error in main.cpp

### ISSUE THREAD

**Issue by cameronscene** [Frain-Breeze/kon-psp-tools#1]
when i try to compile it with "make -j2" after the cmake successfully initiated, i have this message at the near end of the compilation

/home/damien/Vidéos/K-ON/teatimetools/teatimetools/src/main.cpp: Dans la fonction « bool proc::digitalcute_bin_test(settings&) »:
/home/damien/Vidéos/K-ON/teatimetools/teatimetools/src/main.cpp:411:20: erreur: « class DigitalcuteArchive » n'a pas de membre nommé « write_bin »; vouliez-vous utiliser « write_dir » ?
  411 |                 ar.write_bin(fdo, false);
      |                    ^~~~~~~~~
      |                    write_dir
make[2]: *** [teatimetools/CMakeFiles/teatimetools.dir/build.make:76 : teatimetools/CMakeFiles/teatimetools.dir/src/main.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:1705 : teatimetools/CMakeFiles/teatimetools.dir/all] Erreur 2
make: *** [Makefile:136 : all] Erreur 2

this is in french, hope you can fix it :3

**Comment by Frain-Breeze** [comment]
fixed in 1a46f8da557ddabb2d1031d953177acbae9320a3
