### ISSUE TITLE
How to use teatimetools?

### ISSUE THREAD

**Issue by Deochan** [Frain-Breeze/kon-psp-tools#2]
I do not know this programming language well, but I have a desire to translate the game into my own language.  I want to know how to launch a terminal window and use it

**Comment by Frain-Breeze** [comment]
the program is not really user-friendly at the moment, it would be easier if you joined the discord at https://discord.gg/EuyjFsCn5Y where i can assist directly

**Comment by Deochan** [comment]
Ok thx
